CREATE TABLE livro(

	id_livro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	titulo VARCHAR(254),
	autor VARCHAR(254),
	ano_publicacao integer

);

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('IT','IT A COISA','1400');

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('Rari do poti','o poti','5555');

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('Lula o ladrão','Pessoas inteligentes','1945');

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('13 motivos para votar no PT ','Pessoa que tem cerebro','1945');

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('22 motivos para votar no Bolsonaro','Pessoa que é inteligente','1955');



