CREATE TABLE livro(

	id_livro integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	titulo VARCHAR(254),
	autor VARCHAR(254),
	ano_publicacao integer

);

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('IT','IT A COISA','1400');

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('Rari do poti','o poti','5555');

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('Lula o ladrão','Pessoas inteligentes','1945');

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('13 motivos para votar no PT ','Pessoa que tem cerebro','1945');

INSERT INTO livro(titulo, autor, ano_publicacao) 
VALUES ('22 motivos para votar no Bolsonaro','Pessoa que é inteligente','1955');



SELECT id_livro, titulo, autor, ano_publicacao FROM livro




CREATE TABLE usuario(

	id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(254),
	usuario varchar(254),
	senha_hash VARCHAR(12)

);

DROP TABLE USUARIO 


INSERT INTO usuario (nome, usuario, senha_hash)
VALUES ('Ana Silva', 'ana.silva', 'a1b2c3d4e5f');

INSERT INTO usuario (nome, usuario, senha_hash)
VALUES ('Bruno Costa', 'bruno.costa', 'hash123456');

INSERT INTO usuario (nome, usuario, senha_hash)
VALUES ('Carla Mendes', 'carla.m', 'senhaabc12');

INSERT INTO usuario (nome, usuario, senha_hash)
VALUES ('Diego Rocha', 'diego.rocha', 'dr2024hash');

INSERT INTO usuario (nome, usuario, senha_hash)
VALUES ('Eduarda Lima', 'eduarda.l', 'edlima9876');
